name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      - name: Login to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_MAGNI }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD_MAGNI }}
        run: docker login -u $DOCKER_USER_MAGNI -p $DOCKER_PASSWORD_MAGNI

      - name: Build the Docker image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_MAGNI }}
        run: docker build . -f CatalogService/Dockerfile -t ${DOCKER_USER_MAGNI}/catalogserviceapi:latest-dev

      - name: Push Docker image to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_MAGNI }}
        run: docker push ${DOCKER_USER_MAGNI}/catalog-serviceapi:latest-dev
